image:
  repository: ghcr.io/lsdopen/archy
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  defaultArch: amd64
  logLevel: info
  cacheTimeout: 300s

tls:
  certManager: true
  issuer: selfsigned-issuer

webhook:
  failurePolicy: Ignore
  timeoutSeconds: 10
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values: ["kube-system", "kube-public", "kube-node-lease"]

service:
  type: ClusterIP
  webhook:
    port: 443
    targetPort: 8443
  metrics:
    port: 8080
    targetPort: 8080

serviceAccount:
  create: true
  name: ""

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
    - ALL

nodeSelector: {}
tolerations: []
affinity: {}

monitoring:
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
    metricRelabelings: []
    relabelings: []
  
  prometheusRule:
    enabled: false
    labels: {}