run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
  gosec:
    severity: medium
    confidence: medium
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - gocyclo
    - gocognit
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - exportloopref
    - nolintlint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false