{{- if .Values.tls.certManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "archy.fullname" . }}-certs
  labels:
    {{- include "archy.labels" . | nindent 4 }}
spec:
  secretName: {{ include "archy.fullname" . }}-certs
  issuerRef:
    name: {{ .Values.tls.issuer }}
    kind: ClusterIssuer
  dnsNames:
  - {{ include "archy.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "archy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}