apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: {{ include "archy.fullname" . }}
  labels:
    {{- include "archy.labels" . | nindent 4 }}
  {{- if .Values.tls.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "archy.fullname" . }}-certs
  {{- end }}
spec:
  clientConfig:
    service:
      name: {{ include "archy.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  namespaceSelector:
    {{- toYaml .Values.webhook.namespaceSelector | nindent 4 }}