apiVersion: v1
kind: Service
metadata:
  name: archy-webhook
  namespace: archy-system
  labels:
    app: archy-webhook
spec:
  selector:
    app: archy-webhook
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP