name: Main Branch

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: |
        go mod tidy
        go test -v -race -coverprofile=coverage.out ./...
    
    - name: Build multi-arch binaries
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/webhook-linux-amd64 ./cmd/webhook
        GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o bin/webhook-linux-arm64 ./cmd/webhook
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 19
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}